use_frameworks!

platform :ios, '8.0'

target 'DSCapture_Example' do
  pod 'DSCapture', :path => '../'

  target 'DSCapture_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
